name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 4.8
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish MultiUserAddressBook_NTier.sln -c Release -o website
    - uses: actions/checkout@v1
    - name: mkdir
    - run: mkdir -p path/to/artifact


    - uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: path/to/artifact
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: website
        path: path/to/artifact
        if-no-files-found: error
